Lightwerk:
  SurfCaptain:
    # use a github repo (in future we will also support FLOW Repos)
    presets:
      repositoryUrl: git@github.com:achimfritz/Test.git

    # we log(for debugging) and save(for OfflineRequest(s. Objects.yaml)) all requests
    gitApi:
      requestListener:
        save: TRUE
        log: TRUE

    sources:
      git.lightwerk.com:
        # we have new drivers
        className: \Lightwerk\SurfCaptain\GitApi\Driver\GitLabDriver
        # we need an accountName
        accountName: git@git.lightwerk.com
        # we have cool/flexibles repositories
        repositories:
          lwProjects: groups/10
          lwEtc: groups/7
          single: projects/209
      git.sma.de:
        className: \Lightwerk\SurfCaptain\GitApi\Driver\GitLabDriver
        accountName: git@git.sma.de
        repositories:
          smaRcw: projects/2
          # see above
          websites: groups/4
      # we have full supported github
      github.com: 
        privateToken: 'you know what do do'
        apiUrl: https://api.github.com/ 
        className: \Lightwerk\SurfCaptain\GitApi\Driver\GitHubDriver
        accountName: git@github.com
        mapping: 
          Repository: 
            repositoryUrl: '{{ssh_url}}' 
            webUrl: '{{url}}' 
          Commit:
            id: '{{sha}}'
# message committer and date missing (additional request neccessary
        repositories:
          af: users/achimfritz/repos
          lm: users/lars85/repos
          lw: orgs/lightwerk/repos
          single: repos/achimfritz/championship-distribution

