Lightwerk:
  SurfCaptain:

    # Flow passes these settings directly to the angular single page application
    frontendSettings:
      # Default ssh user for deployments
      defaultUser: 'lw-deployment'
      # Target path for deployments (without '../htdocs')
      defaultDeploymentPath: '/var/www/{{project}}/{{suffix}}/'
      # Contexts starting with these main contexts are valid
      # Further subdivisions are possible with subcontexts (of example: 'Production/Qa')
      contexts: 'Production,Testing,Development'
      # Offer these contexts as suggestions for new servers
      nameSuggestions:
        live: 'Production'
        qa: 'Production/Qa'
        staging: 'Production/Staging'
        test: 'Testing'
        dev: 'Development'

    gitApi:
      requestListener:
        save: FALSE
        log: FALSE

    # Configures sources of the git repositories
    sources:
      # See Packages/Application/Lightwerk.SurfCaptain/Configuration/Settings.yaml.example

    repository:
      # Presets are preconfigured deployment configurations (usually on per server).
      # Default is fileRepository. Change the default in Configuration/Objects.yaml.
      preset:
        fileRepository:
          filePath: 'Configuration/Presets.json'
TYPO3:
  Setup:
    stepOrder: ['database', 'gitdriver', 'gitsettings', 'deployment', 'verification', 'final']
    steps:
      gitdriver:
        className: 'Lightwerk\SurfCaptain\Setup\Step\GitDriverStep'
      gitsettings:
        className: 'Lightwerk\SurfCaptain\Setup\Step\GitSettingsStep'
      deployment:
        className: 'Lightwerk\SurfCaptain\Setup\Step\DeploymentStep'
      verification:
        className: 'Lightwerk\SurfCaptain\Setup\Step\VerificationStep'
      final:
        className: 'Lightwerk\SurfCaptain\Setup\Step\FinalStep'
    view:
      title: 'Lightwerk SurfCaptain Setup'

