Lightwerk:
  SurfCaptain:
    presets:
      repositoryUrl: git@git.lightwerk.com:lm/lightwerk-surfcaptain-settings.git
      filePath: Presets.json
    sources:
      git.lightwerk.com:
        className: \Lightwerk\SurfCaptain\Service\Driver\GitLabDriver
        privateToken: 'Please define this value in root/Configuration/Settings.yaml'
        url: https://git.lightwerk.com/api/v3/
        repositories:
          _projectFilter:
            groupIds:
              - 10
#      git.sma.de:
#        className: \Lightwerk\SurfCaptain\Service\Driver\GitLabDriver
#        privateToken: 'Please define this value in root/Configuration/Settings.yaml'
#        url: http://git.sma.de/api/v3/
#        repositories:
#          _rcwSmaDeFilter:
#            repositoryUrls:
#              - git@git.sma.de:sma-websites/rcw-sma-de.git