Lightwerk:
  SurfCaptain:
    frontendSettings:
      defaultUser: 'lw-deployment'
      defaultDeploymentPath: '/var/www/{{project}}/{{suffix}}/'
      contexts: 'Production,Testing,Development'
      nameSuggestions:
        live: 'Production'
        qa: 'Production/Qa'
        staging: 'Production/Staging'
        test: 'Testing'
        dev: 'Development'

    gitApi:
      requestListener:
        save: FALSE
        log: FALSE